# Generated by Django 4.1 on 2023-03-09 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='customerReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('review', models.TextField()),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'customerReviews',
            },
        ),
        migrations.CreateModel(
            name='Imagesuploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Allimages', models.ImageField(upload_to='myimages')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('caption', models.TextField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Imagesuploader',
            },
        ),
        migrations.CreateModel(
            name='diaryentries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dailydate', models.DateField()),
                ('dailytime', models.TimeField()),
                ('place', models.CharField(blank=True, max_length=150, null=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('dailyentry', models.CharField(max_length=1500)),
                ('check_box', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='myimages')),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'diaryentries',
            },
        ),
    ]
